export const newsLinks = [
  "https://www.stevanilab.com/single-post/2015/03/23/why-some-mushrooms-glow-in-the-dark",
  "https://www.stevanilab.com/single-post/2019/05/13/pesquisadores-descobrem-sistema-bioluminescente-codificável",
  "https://www.stevanilab.com/single-post/2015/02/13/glow-in-the-dark-mushrooms-nature-s-night-lights",
  "https://www.stevanilab.com/single-post/2011/08/07/scientists-rediscover-glowing-mushrooms",
  "https://www.stevanilab.com/single-post/2017/05/02/glowing-mushroom-discovery-could-revolutionize-biology",
  "https://www.stevanilab.com/single-post/2006/10/27/photo-gallery-new-glowing-mushrooms-found-in-brazil",
  "https://www.stevanilab.com/single-post/2015/03/26/cientistas-descobrem-que-fungo-que-brilha-no-escuro-tem-relógio-biológico",
  "https://www.stevanilab.com/single-post/2010/10/08/forscher-finden-sieben-neue-leuchtpilze",
  "https://www.stevanilab.com/single-post/2015/03/20/why-some-mushrooms-glow-in-the-dark",
  "https://www.stevanilab.com/single-post/2017/05/02/lumière-sur-les-champignons-brillants",
  "https://www.stevanilab.com/single-post/2015/01/21/célula-solar-polimérica-resultados-laboratoriais",
  "https://www.stevanilab.com/single-post/2019/11/01/first-bioluminescent-insect-that-glows-blue-in-south-america-discovered",
  "https://www.stevanilab.com/single-post/2017/04/26/cientistas-iluminam-segredo-dos-cogumelos-que-brilham-no-escuro",
  "https://www.stevanilab.com/single-post/want-to-see-glow-in-the-dark-mushrooms-visit-brazil-s-other-rain-forest",
  "https://www.stevanilab.com/single-post/2018/11/27/scientists-uncovered-the-mechanism-of-fungal-luminescence-and-created-luminescent-yeasts",
  "https://www.stevanilab.com/single-post/2011/07/11/cogumelo-que-emite-luz-é-encontrado-no-brasil-após-170-anos-1",
  "https://www.stevanilab.com/single-post/2011/11/18/noite-revela-cogumelos-luminosos-e-mariposa-com-língua-de-20-cm",
  "https://www.stevanilab.com/single-post/menor-cogumelo-bioluminescente-do-mundo-é-encontrado-no-parque-estadual-caverna-do-diabo-terra-da-g",
  "https://www.stevanilab.com/single-post/2019/09/30/inseto-sul-americano-que-emite-luz-azul-é-descoberto-por-brasileiros",
  "https://www.stevanilab.com/single-post/2011/06/13/last-years-top-10-new-species",
  "https://www.stevanilab.com/single-post/2010/02/02/luzes-vivas",
  "https://www.stevanilab.com/single-post/2017/04/27/hunting-mushrooms-and-what-makes-some-glow-in-the-dark",
  "https://www.stevanilab.com/single-post/2011/05/24/espécies-descobertas-em-2010-são-listadas-por-universidade",
  "https://www.stevanilab.com/single-post/2019/08/12/larva-brilhante-e-raríssima-é-descoberta-por-cientistas-em-sp",
  "https://www.stevanilab.com/single-post/2013/06/16/lost-in-the-light",
  "https://www.stevanilab.com/single-post/organismo-marinho-tem-fotoproteína-verde-desconhecida",
  "https://www.stevanilab.com/single-post/2015/03/19/dude-why-is-my-mushroom-glowing-scientists-have-the-answer",
  "https://www.stevanilab.com/single-post/2017/06/12/como-fungos-usam-química-para-brilhar-no-escuro-da-mata",
  "https://www.stevanilab.com/single-post/2011/07/11/após-170-anos-cogumelo-que-emite-luz-é-encontrado-no-brasil",
  "https://www.stevanilab.com/single-post/bioluminescência-pode-ser-alternativa-sustentável-para-iluminar-ambientes-urbanos",
  "https://www.stevanilab.com/single-post/2017/04/26/come-fanno-i-funghi-a-brillare-al-buio",
  "https://www.stevanilab.com/single-post/2017/04/29/was-pilze-im-dunkeln-leuchten-lässt",
  "https://www.stevanilab.com/single-post/2017/04/26/heres-why-these-mushrooms-glow-in-the-dark",
  "https://www.stevanilab.com/single-post/brilho-diabólico-fotolab-pesquisa-fapesp",
  "https://www.stevanilab.com/single-post/2015/03/19/ritmo-biológico-controla-brilho-de-cogumelos",
  "https://www.stevanilab.com/single-post/why-do-some-mushrooms-glow",
  "https://www.stevanilab.com/single-post/2011/05/24/fungo-brasileiro-está-entre-as-espécies-mais-significativas-de-2010",
  "https://www.stevanilab.com/single-post/2017/04/26/iluminação-natural",
  "https://www.stevanilab.com/single-post/2016/04/08/circadian-control-sheds-light-on-fungal-bioluminescence",
  "https://www.stevanilab.com/single-post/terra-da-gente-estado-de-sp-tem-maior-concentração-de-cogumelos-bioluminescentes-do-mundo",
  "https://www.stevanilab.com/single-post/2014/07/30/minha-pesquisa-sobre-ativação-do-peróxido-de-hidrogênio",
  "https://www.stevanilab.com/single-post/2008/08/15/a-thousand-points-of-light-bioluminescent-fungi",
  "https://www.stevanilab.com/single-post/2019/08/12/descoberta-científica-coloca-iporanga-no-centro-das-atenções",
  "https://www.stevanilab.com/single-post/2009/10/05/flashy-fungi-researchers-still-in-the-dark-over-glowing-jungle-mushrooms",
  "https://www.stevanilab.com/single-post/2017/04/26/illuminating-the-secret-of-glow-in-the-dark-mushrooms-mechanism-and-color-modulation-of-f",
  "https://www.stevanilab.com/single-post/2015/03/19/glowing-mushroom-attracts-insects",
  "https://www.stevanilab.com/single-post/2017/05/08/processo-químico-da-bioluminescência-de-fungos-é-reciclável-e-flexível",
  "https://www.stevanilab.com/single-post/2011/07/07/lost-glow-in-the-dark-ghost-mushrooms-rediscovered",
  "https://www.stevanilab.com/single-post/2009/11/03/luz-na-escuridão",
  "https://www.stevanilab.com/single-post/2011/06/17/ilustres-desconhecidos",
  "https://www.stevanilab.com/single-post/hiperconectado-bioluminescência",
  "https://www.stevanilab.com/single-post/what-a-bioluminescent-petunia-had-to-teach-me",
  "https://www.stevanilab.com/single-post/2015/03/19/dieser-pilz-knipst-nicht-umsonst-das-licht-an",
  "https://www.stevanilab.com/single-post/2015/03/19/far-out-man-scientists-figure-out-why-some-mushrooms-glow",
  "https://www.stevanilab.com/single-post/2005/08/29/usp-acha-cogumelos-luminosos-no-brasil",
  "https://www.stevanilab.com/single-post/2015/03/25/licht-unterstützt-die-ausbreitung",
  "https://www.stevanilab.com/single-post/2017/04/27/how-a-mushroom-gets-its-glow",
  "https://www.stevanilab.com/single-post/2015/05/21/pesquisadores-brasileiros-desvendam-como-o-cogumelo-flor-de-coco-se-ilumina",
  "https://www.stevanilab.com/single-post/glowy-fungi-illuminate-the-path-to-understanding-bioluminescence",
  "https://www.stevanilab.com/single-post/2015/10/12/luzes-vivas-da-noite",
  "https://www.stevanilab.com/single-post/2011/07/07/mushroom-lights-up-the-night-in-brazil-researcher-finds-bioluminescent-fungus-not-seen-si",
  "https://www.stevanilab.com/single-post/2017/05/03/heres-the-secret-of-glow-in-the-dark-mushrooms-not-so-magical-after-all",
  "https://www.stevanilab.com/single-post/2009/06/25/o-universo-luminoso-dos-fungos-bioluminescentes",
  "https://www.stevanilab.com/single-post/2011/05/24/top-ten-new-species-walking-fish-t-rex-leech-more",
  "https://www.stevanilab.com/single-post/2015/03/19/bizarrer-pilz-lockt-nachts-mit-grünen-strahlen",
  "https://www.stevanilab.com/single-post/2018/02/19/at-long-last-a-stamp-of-approval-for-mushrooms",
  "https://www.stevanilab.com/single-post/2019/09/18/descoberto-o-primeiro-inseto-sul-americano-que-emite-luz-azul",
  "https://www.stevanilab.com/single-post/2017/05/12/greening-preprint-chip-e-bioluminescência",
  "https://www.stevanilab.com/single-post/2016/07/03/how-research-into-glowing-fungi-could-lead-to-trees-lighting-our-streets",
  "https://www.stevanilab.com/single-post/2018/11/28/scientists-discovered-a-set-of-enzymes-to-create-glowing-organisms",
  "https://www.stevanilab.com/single-post/2015/03/19/in-der-nacht-geht-das-licht-an",
  "https://www.stevanilab.com/single-post/2011/07/11/cogumelo-que-emite-luz-é-encontrado-no-brasil-após-170-anos",
  "https://www.stevanilab.com/single-post/2015/03/20/glowing-mushrooms",
  "https://www.stevanilab.com/single-post/2012/06/28/ted-talk-nature-s-bioluminescent-mushrooms",
  "https://www.stevanilab.com/single-post/2017/04/26/el-secreto-de-los-hongos-bioluminiscentes",
  "https://www.stevanilab.com/single-post/2015/08/11/circadian-rhythm-in-fungal-bioluminescence-natures-bright-idea",
  "https://www.stevanilab.com/single-post/2018/11/27/das-geheimnis-der-leuchtpilze",
  "https://www.stevanilab.com/single-post/2019/09/12/o-mosquito-brilhante-do-vale-do-ribeira",
  "https://www.stevanilab.com/single-post/pesquisador-responde-perguntas-sobre-os-cogumelos-brilhantes",
  "https://www.stevanilab.com/single-post/2015/03/23/mushrooms-that-glow-to-continue-the-species",
  "https://www.stevanilab.com/single-post/levantamentos-de-organismos-bioluminescentes-geram-propostas-turísticas",
  "https://www.stevanilab.com/single-post/2017/05/09/montadoras-vs-libélulas",
  "https://www.stevanilab.com/single-post/2018/12/05/brilho-construído",
  "https://www.stevanilab.com/single-post/2009/10/05/glowing-mushroom-pictures-psychedelic-new-species-seen",
  "https://www.stevanilab.com/single-post/2015/03/20/leuchtpilze-locken-insekten-an",
  "https://www.stevanilab.com/single-post/2017/01/27/quiz-on-bioluminescent-creatures",
  "https://www.stevanilab.com/single-post/2009/10/06/biólogos-descobrem-sete-novas-espécies-de-cogumelos-fosforescentes",
  "https://www.stevanilab.com/single-post/antonina-do-pôr-do-sol-ao-amanhecer-parte-1",
  "https://www.stevanilab.com/single-post/2015/03/25/cogumelo-do-brasil-brilha-à-noite-e-os-insectos-vão-até-lá",
  "https://www.stevanilab.com/single-post/2015/03/19/some-mushrooms-glow-and-heres-why"
] as const;

export const legacyPages = [
  ["LUMM — Luminescent Mushroom Database", "https://lumm.uneb.br/en"],
  ["Research projects", "https://www.stevanilab.com/projetos"],
  ["Environmental metagenomics", "/environmental-metagenomics"],
  ["Team", "https://www.stevanilab.com/time"],
  ["Team — English", "https://www.stevanilab.com/team"],
  ["Publications", "/publications"],
  ["News", "https://www.stevanilab.com/noticias-news"],
  ["Contact", "https://www.stevanilab.com/contato"],
] as const;
